# view. 원소의 개수를 유지하며 텐서의 크기를 변경

# numpy의 reshape 와 유사

In [2]:
import numpy as np
import torch

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft)
print(ft.size())

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


# view를 사용해 3차원 텐서 -> 2차원 행렬

In [3]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [4]:
print(ft.view([-1, 6, 1]))


tensor([[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.]]])


# view를 사용해 원소 수를 유지하며 reshape

In [3]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).size())

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# 스퀴즈 - 1인 차원을 제거한다.

In [4]:
ft = torch.FloatTensor([[0],
                        [1],
                        [2]])

print(ft)
print(ft.size())

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# Unsqueeze - 특정 위치에 1인 차원을 추가

In [8]:
ft = torch.FloatTensor([0, 1, 2])
print(ft)
print(ft.size())

tensor([0., 1., 2.])
torch.Size([3])


In [10]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).size())

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).size())

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#  자료형
### torch.FloatTensor - 32bit 부동 소수점
### torch.LongTensor - 64bit 정수
### torch.cuda.FloatTensor - GPU 연산 자료형

In [12]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [14]:
print(lt.float()) # long -> float

tensor([1., 2., 3., 4.])


In [15]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [17]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# concatenate

In [18]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = torch.FloatTensor([[5, 6],
                       [7, 8]])

In [20]:
print(torch.cat([x, y], dim = 0)) # dim = 0은 첫번째 차원을 늘려서 연결
print(torch.cat([x, y], dim = 0).size())

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


In [21]:
print(torch.cat([x, y], dim = 1)) # dim = 1은 두번째 차원을 늘려서 연결
print(torch.cat([x, y], dim = 1).size())

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


# Stacking

In [22]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [24]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [25]:
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# ones_like, zeros_like

In [26]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [27]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation 

In [30]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

print(x.mul(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [32]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
