# numpy - 1차원 벡터 생성

In [8]:
import numpy as np

t = np.array([1,2,3,4,5,6,7,8,9])

print(t)
print('Rank of t :', t.ndim)
print('size of t :', t.shape)

[1 2 3 4 5 6 7 8 9]
Rank of t : 1
size of t : (9,)


# numpy - 2차원 행렬 생성

In [7]:
t2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(t2)
print('Rank of t :', t2.ndim)
print('Size of t :', t2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of t : 2
Size of t : (3, 3)


# torch - 1차원 벡터 생성

In [12]:
import torch

t = torch.FloatTensor([0,1,2,3,4,5,6,7,8,9])

print(t)
print('Rank of t :', t.dim())
print('Size of t :', t.size())

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Rank of t : 1
Size of t : torch.Size([10])


# torch - 2차원 행렬 생성

In [13]:
t2 = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

print(t2)
print('Rank of t :', t2.dim())
print('Size of t :', t2.size())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Rank of t : 2
Size of t : torch.Size([3, 3])


In [17]:
print(t2[:,2])
print(t2[:,2].size())

tensor([3., 6., 9.])
torch.Size([3])


# 브로드캐스팅 (Broadcasting)

In [18]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3,4])

print(m1 + m2)

tensor([4., 6.])


In [ ]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([10])

print(m1 + m2)

In [22]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3], [4]])

print(m1)
print(m2)

print(m1 + m2)

tensor([1., 2.])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


# 행렬 곱셈 .matmul 과 원소별 곱셈 .mat

In [23]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # m1 x m2

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [24]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


# mean, sum, max, argmax

# 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴.

In [25]:
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])

In [40]:
print("평균 :", m1.mean())
print("각 열의 평균 :", m1.mean(dim = 0)) # dim = 0 -> 행을 제거
print("각 행의 평균 :", m1.mean(dim = 1)) # dim = 1 -> 열을 제거 

print()
print("합 :", m1.sum())
print("각 열의 합 :", m1.sum(dim = 0))
print("각 행의 합 :", m1.sum(dim = 1))

print()
print("최댓값 : ", m1.max())
print("각 열의 최대값 :", m1.max(dim = 0))
print('Max: ', m1.max(dim=0)[0])
print('Argmax: ', m1.max(dim=0)[1])

평균 : tensor(2.5000)
각 열의 평균 : tensor([2., 3.])
각 행의 평균 : tensor([1.5000, 3.5000])

합 : tensor(10.)
각 열의 합 : tensor([4., 6.])
각 행의 합 : tensor([3., 7.])

최댓값 :  tensor(4.)
각 열의 최대값 : torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
