## 1-1

In [6]:
list1 = [1, 2, 3]

print("type of list1 :", type(list1))
print("[0], [-1] :", list1[0], list1[-1])

print()
list1[1] = "str1"
list2 = range(10)
print("type of list2 :", type(list2))

print()
list2 = list(list2)
print("type of list2 :", type(list2))

type of list1 : <class 'list'>
[0], [-1] : 1 3

type of list2 : <class 'range'>

type of list2 : <class 'list'>


## 1-2

In [12]:
print("list2[2:4] :", list2[2:4])
print("list2[2:] :", list2[2:])
print("list2[:2] :", list2[:2])
print("list2[:] :", list2[:])
print("list2[::2] :", list2[::2])
print("list2[:-1] :", list2[:-1])
print()

list2[2:4] = [8, 9]
list2[2:5] = [8, 9]

print(list2)

list2[2:4] : [8, 9]
list2[2:] : [8, 9, 5, 6, 7, 8, 9]
list2[:2] : [0, 1]
list2[:] : [0, 1, 8, 9, 5, 6, 7, 8, 9]
list2[::2] : [0, 8, 5, 7, 9]
list2[:-1] : [0, 1, 8, 9, 5, 6, 7, 8]

[0, 1, 8, 9, 6, 7, 8, 9]


## 1-3

In [14]:
animals =['cat', 'dog', 'monkey']

for animals in animals :
    print(animals)
    
nums = [0, 1, 2, 3, 4]
squares = []

for x in nums :
    squares.append(x)
print(squares)

cat
dog
monkey
[0, 1, 2, 3, 4]


## 1-4

In [15]:
def sign(x):
    if x > 0 :
        return 'positive'
    elif x < 0 :
        return 'negative'
    else :
        return 'zero'
    
for x in [-1, 0, 1] :
    print(sign(x))

negative
zero
positive


## 1-5

In [16]:
def hello(name, loud = False) :
    if loud :
        print('HELLO, %s' % name.upper())
    else :
        print('Hello, %s' % name)
        
hello('Bob')

hello('Fred', loud = True)


Hello, Bob
HELLO, FRED


## 1-6

In [19]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

for x, y in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)
    
# z에 해당하는 객체가 for 인자 안에 존재하지 않음.


1 4 7
2 5 8
3 6 9


ValueError: too many values to unpack (expected 2)

## 1-7

In [20]:
class HelloWorld() :
    def __init__ (self) :
        print("init")
        
hellworld = HelloWorld()

# __init__ 은 인스턴스를 호출할 때 따로 메소드를 사용하지 않고도 자동 호출되는 함수이다.


init


## 1-8

In [24]:
class HelloWorld() :
    def __init__(self):
        print("init")
        
helloworld = HelloWorld()

callable(helloworld)

class HelloWorld() :
    def __init__(self) :
        print("init")
        
    def __call__(self) :
        print("Hello World")

helloworld = HelloWorld()
helloworld()

init
init
Hello World


## __init__ 과 __call__ 의 차이.
#### : init 은 객체를 클래스에 할당하면 호출하지 않아도 자동호출 되는 반면, 
#### call 은 인스턴스를 호출해야 비로소 호출된다.

# 1-9

In [29]:
import numpy as np

a = np.array([1, 2, 3])
print("type(a) :", type(a))
print("a.shape :", a.shape)
print("a.ndim :", a.ndim)
print("a[0], a[1], a[2] :", a[0], a[1], a[2])
a[0] = 5
print("a :", a)
print()

b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("b.shape :", b.shape)
print("b.ndim :", b.ndim)
print("b[0, 0], b[0, 1], b[1, 0] :", b[0, 0], b[0, 1], b[1, 0])

type(a) : <class 'numpy.ndarray'>
a.shape : (3,)
a.ndim : 1
a[0], a[1], a[2] : 1 2 3
a : [5 2 3]

b.shape : (2, 3)
b.ndim : 2
b[0, 0], b[0, 1], b[1, 0] : 1 2 4


# 1-10

In [33]:
a = np.zeros((2, 2))
print(a)
print()

b = np.ones((1, 2))
print(b)
print()

c= np.full((2, 2), 7)
print(c)
print()

d = np.eye(2)
print(d)
print()

e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]

[[1. 1.]]

[[7 7]
 [7 7]]

[[1. 0.]
 [0. 1.]]

[[0.77714078 0.97992905]
 [0.81006059 0.25354547]]


# 1-11

In [38]:
a = np.arange(10)
print(np.where(a < 5))
print(np.where(a < 5, a, 10 * a)) # a < 5 를 찾아서 True => 그대로, False => X 10
print(np.where(a < 4, a, -1))

(array([0, 1, 2, 3, 4], dtype=int64),)
[ 0  1  2  3  4 50 60 70 80 90]
[ 0  1  2  3 -1 -1 -1 -1 -1 -1]


# 1-12

In [48]:
a =np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

b = a[:2, 1:3] 
print(b)

print("a[0, 1] :", a[0, 1])

b[0, 0] =77
print("a[0, 1] :", a[0, 1]) # .copy() 사용시 다른 메모리에 저장되어 a의 값 불변


[[2 3]
 [6 7]]
a[0, 1] : 2
a[0, 1] : 77


# 1-13

In [49]:
a =np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

b = np.reshape(a, (2, 6))
print(b)

print("a[0, 1] :", a[0, 1])

b[0, 0] =77
print("a[0, 1] :", a[0, 1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a[0, 1] : 2
a[0, 1] : 2


# 1-14

In [51]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

np.dot(a, b)

array([[4, 1],
       [2, 2]])

# 1.15

In [54]:
import torch
import numpy as np

t1 = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6,])
t2 = torch.FloatTensor(np.arange(7))

print(t1.shape)
print(t2.shape)
print(t1.dim())
print(t2.size())
print(t1[:2])
print(t1[3:])

torch.Size([7])
torch.Size([7])
1
torch.Size([7])
tensor([0., 1.])
tensor([3., 4., 5., 6.])


# 1-16

In [57]:
b = np.arange(7)
t1 = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(type(b))
print(type(t1))

tt = torch.tensor(b) # b를 copy한 객체
t_from = torch.from_numpy(b) # b와 같은 메모리에 저장

print(type(tt))
print(type(t_from))
print(tt)
print(t_from)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32)
tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32)


# 1-17

In [59]:
b[0] = -10
print(tt)
print(t_from)

t_to_np = t_from.numpy()
print(type(t_to_np))

tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32)
tensor([-10,   1,   2,   3,   4,   5,   6], dtype=torch.int32)
<class 'numpy.ndarray'>


# 1-18

In [64]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])

print(m1 + m2)

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

print(m1 + m2)

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


# 1-19

In [66]:
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])

print(m1 * m2)
print(m1.mul(m2))
print(m1.matmul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[ 5.],
        [11.]])


# 1-20

In [73]:
t = np.arange(12).reshape(-1, 2, 3) # (2, 2, 3)
print(t, t.shape)

floatT = torch.FloatTensor(t)
print(floatT.shape)
print()

print(floatT.view([-1, 3])) # (4, 3)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
torch.Size([2, 2, 3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
