In [14]:
import numpy as np

# 2-1
a = np.arange(50)
print(a)
print()

# 2-2
b = np.arange(49, 9, -1)
print(b)
print()

# 2-3
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(A == B, A, 0))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

[0 2 0 2 0 4 0 4 0 0]


In [28]:
# 2-4 
a = np.arange(9).reshape(3, 3)
b = 1
print(a + b)

# 2-5
c = a.copy()
c_1 = c[0, :] ; c_2 = c[1, :]
a[0, :] = c_2
a[1, :] = c_1
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [32]:
# 2-6
a = np.arange(0, 24).reshape(2, 3, 4)
print("shape :", a.shape)
print("value :", a)\

# 2-7
print(a[0][1:3, 2:4])

shape : (2, 3, 4)
value : [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 6  7]
 [10 11]]


In [42]:
# 2-8
import torch
 
t = np.arange(24)
print(t.shape)

floatT = torch.FloatTensor(t)
print(floatT.view([-1,3])[4:8,1])

(24,)
tensor([13., 16., 19., 22.])
